server:
  port: 8090
spring:
  application:
    name: activemq_procuder

  activemq:
    broker-url: tcp://10.222.29.171:61617
    user: admin
    password: admin
    #after activeMq 5.15, in order to improve the security, activeMq will not trust the custom serialized objects, so need add below config to accept the object class
    packages:
      trust-all: true

  #(PTP => false, Topic => true)
  jms:
    pub-sub-domain: true
    template:
      delivery-mode: persistent #非持久化模式

