server:
  port: 8091
spring:
  application:
    name: activemq_procuder

  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    #after activeMq 5.15, in order to improve the security, activeMq will not trust the custom serialized objects, so need add below config to accept the object class
    packages:
      trust-all: true
      
  #(PTP => false, Topic => true)
  jms:
    pub-sub-domain: false
    template:
      delivery-mode: persistent